// autogenerated with
// python tp_codegen.py
// #ifndef INCLUDED_TP_H
// #define INCLUDED_TP_H

void tp_v2(int l1, int l2, int l3, const float* input1, const float* input2, float* output);

// #endif // ifndef INCLUDED_TP_H
